import './globals.css';

export const metadata = {
  title: 'Calientes 🌶️: Hot Ones App',
  description: 'Generated by Juan Cabrera and Andrew Smith',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-dark d-flex flex-column justify-content-between align-items-center min-vh-100">
        {children}
      </body>
    </html>
  );
}
