import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Testing...',
  description: 'Generated by create next app',
};

export default function TestingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <section>{children}</section>
    </>
  );
}
